### ISSUE TITLE
Speed up Nessie integration tests

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#2033]
They take too long.  Target is <= 10m "pass", <= 5m "excellent".

Blanket for these PRs & issues:
- [x] #1926 (i) #2010 (PR): cache docker
- [x] #2023 (PR): run in parallel on all the clouds
- [x] #2032 (PR): generate code once

**Comment by arielshaqed** [comment]
Still takes (just) over 10m.  Time usage of a recent flow:
![time usage of jobs in Nessie workflow](https://user-images.githubusercontent.com/7802932/120304259-4ddd3800-c2d8-11eb-8645-94a4da87f1c5.png)

Everything flows through "generate code", which takes 2m5s, and then "build and push Docker", which takes 3m50s. Other than that, "test lakeFS with Spark" takes 5m9s, and "Run latest lakeFS on AWS S3" takes 5m46s.  They (can) run in parallel.

Options:
1. Speed up "build and push Docker".  Pros: non-parallel.  Cons: not clear how much further we can save.
2. "Generate code" inside Docker, which might speed up when cached.  Pros: non-parallel.  Cons: not clear there's much to save, this is what it takes.
3. "Generate code" with `make -j`, which might speed up when _outside_ of Docker.  Pros: cheap, probably harmless.  Cons: not clear we get >1 core on GitHub actions; almost certainly limited to single core in Docker build on GitHub actions, so probably won't work there with the above.
4. Speed up the 2 terminal jobs.  Pros: Take the most time.  Cons: need to speed up _both_ in order to finish faster.

**Comment by arielshaqed** [comment]
Closing this: we're are 10-13m, which is still failing by my criteria above but we're running out of time to do more.  (Still down from >17m, so we're doing much better!)
