### ISSUE TITLE
KV Release checklist

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#3896]
- [x] Merge documentation PR https://github.com/treeverse/lakeFS/pull/3878 to master
	- [x] Add migration version to upgrade docs (const: v0.80.0) @N-o-Z 
	- [x] KV introduction in migration docs @itai-david 
	- [x] DynamoDB AWS deployment @itai-david 
- [x] Remove KV flag from database configuration (Delete initialization of DB in all entry points) **Just need to merge** @itaiad200 
 	- [x] Modify esti lakefs.yaml @itaiad200 
    - [x] Update docker-compose.yaml to work with KV @itaiad200 
- [x] Update Callhome's quickstart docker-compose @nopcoder 
- [x] Prepare changelog message for KV -> link to KV release documentation @itai-david 
- [x] Sync with R&D, product, CS
- [x] Change startup message (when fail due to migration) to migration docs. @itai-david #4001 
- [x] Run Enigma simulation in the SaaS @N-o-Z 
	- [x] Postgres @nopcoder 
	- [x] Validate ListCommits - no repro of bug @itaiad200 
	- [x] Validate Merge - no repro of bug @itaiad200 
	- [x] DynamoDB @eden-ohana 
		- [x] Analyse costs @eden-ohana 
		- [x] Sizing guide for DynamoDB @eden-ohana 
- [x] Blog @nopcoder / @itai-david 
- [x] Playground stats from KV usage @N-o-Z 
	- [x] 	error rate unchanged
	- [x] no performance degradation
	- [x] Number of isolakes
- [x] SaaS migration @itaiad200 
- [x] SaaS new installations to run with KV @itaiad200 
- [x] UnitTest for the playground bug @itai-david 
- [x] Update helm chart and handle update (migrate data from previous version) @itai-david 
- [x] #4028 @nopcoder 
- [x] https://github.com/treeverse/lakeFS/issues/4067  --> PR #4071 
- [x] Increase Needed DB to 20GB @guy-har @itaiad200 
- [x] fix retryBranchUpdate @eden-ohana  
- [x] Database storage full - migration stop @N-o-Z 
- [x] Migration progress logs and Warning @itaiad200 https://github.com/treeverse/lakeFS/pull/4082
- [x] PrepareCommitsForGC comparison @itaiad200 
- [x] #4086 @itaiad200
