### ISSUE TITLE
Python Wrapper: Release checklist

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#7048]
- [x] Verify docs release
- [x] Change documentation title to "Beta" and bump version
- [x] Verify docs host
- [x] Add lakeFS documentation
- [x] Enable release workflow to production PyPI
- [x] Run release workflow
