### ISSUE TITLE
Pull Requests MVP - Tasks Breakdown

### ISSUE THREAD

**Issue by N-o-Z** [treeverse/lakeFS#8166]
### [API and Data Model design](https://github.com/treeverse/lakeFS/issues/8164)

-----

- [x] Proto and Ref manager
    - [x] [~Task 1~](https://github.com/treeverse/lakeFS/issues/8177)
      - [x] Create required protobuf models
      - [x] Add logic to ref manager to get, create, update, delete
      - [x] Unit tests
    - [x] [Task 2](https://github.com/treeverse/lakeFS/issues/8183)
      - [x] Pull requests iterator 
      - [x] List pull requests
      - [x] Unit tests
- [x] Graveler
    - [x] Implement logic for pull requests
    - [x] Unit tests
- [x] Catalog
    - [x] Add logic to catalog to create, update delete and list pull requests
- [x] [~Add Swagger Endpoints~](https://github.com/treeverse/lakeFS/issues/8167)
    - [x] Add swagger definitions and auto generated code
    - [x] Create stubs for Controller 
    - [x] Unit tests
- [x] Controller
    - [x] [~CreatePullRequest~](https://github.com/treeverse/lakeFS/issues/8189)
    - [x] [~ListPullRequests~](https://github.com/treeverse/lakeFS/issues/8197)
    - [x] [~GetPullRequest~](https://github.com/treeverse/lakeFS/issues/8189)
    - [x] [~Pull Requests MVP: Update/Delete Pull Request~](https://github.com/treeverse/lakeFS/issues/8202#top)
    - [x] Unit tests
- [x] Integration Tests
- [x] [Create Pull Requests GUI](https://github.com/treeverse/lakeFS/issues/8172)
  - [x] [List PRs page](https://github.com/treeverse/lakeFS/issues/8173)
  - [x] [Create PR page](https://github.com/treeverse/lakeFS/issues/8174)
  - [x] [View PR page](https://github.com/treeverse/lakeFS/issues/8175)
  - [x] [Edit PR](https://github.com/treeverse/lakeFS/issues/8176)
  - [x] [Wire UI to the API](https://github.com/treeverse/lakeFS/issues/8180)
  - [x] [Review and update the UI](https://github.com/treeverse/lakeFS/issues/8181)
  - [x] [Add Playwright tests](https://github.com/treeverse/lakeFS/issues/8182)

**Comment by N-o-Z** [comment]
@itaigilo Feel free to add tasks breakdown for the GUI task

**Comment by N-o-Z** [comment]
Changing the strategy to implement flows E2E to accommodate the development efforts for the UI
